"""added status yo movie

Revision ID: d4095e97390e
Revises: 273c57fee466
Create Date: 2022-03-15 12:07:58.122872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4095e97390e'
down_revision = '273c57fee466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'status')
    # ### end Alembic commands ###
